# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/py_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lib/py_proto.proto',
  package='api',
  serialized_pb=_b('\n\x12lib/py_proto.proto\x12\x03\x61pi\"F\n\x08\x45rrorDTO\x12$\n\terrorCode\x18\x01 \x02(\x0e\x32\x11.api.ErrorCodeDTO\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x02(\t\"\\\n\nAccountDTO\x12\x12\n\naccountUid\x18\x01 \x02(\t\x12\x13\n\x0b\x61\x63\x63ountName\x18\x02 \x02(\t\x12\x13\n\x0b\x61\x63\x63ountType\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"8\n\x14\x43reateAccountCommand\x12 \n\x07\x61\x63\x63ount\x18\x01 \x02(\x0b\x32\x0f.api.AccountDTO\"\x17\n\x15\x43reateAccountDocument\"(\n\x11GetAccountCommand\x12\x13\n\x0b\x61\x63\x63ountName\x18\x01 \x02(\t\"6\n\x12GetAccountDocument\x12 \n\x07\x61\x63\x63ount\x18\x01 \x02(\x0b\x32\x0f.api.AccountDTO*9\n\x0c\x45rrorCodeDTO\x12\x15\n\x11\x41\x43\x43OUNT_NOT_FOUND\x10\x01\x12\x12\n\x0e\x41\x43\x43OUNT_EXISTS\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ERRORCODEDTO = _descriptor.EnumDescriptor(
  name='ErrorCodeDTO',
  full_name='api.ErrorCodeDTO',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT_NOT_FOUND', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT_EXISTS', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=374,
  serialized_end=431,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODEDTO)

ErrorCodeDTO = enum_type_wrapper.EnumTypeWrapper(_ERRORCODEDTO)
ACCOUNT_NOT_FOUND = 1
ACCOUNT_EXISTS = 2



_ERRORDTO = _descriptor.Descriptor(
  name='ErrorDTO',
  full_name='api.ErrorDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='api.ErrorDTO.errorCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='api.ErrorDTO.errorMessage', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=97,
)


_ACCOUNTDTO = _descriptor.Descriptor(
  name='AccountDTO',
  full_name='api.AccountDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountUid', full_name='api.AccountDTO.accountUid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accountName', full_name='api.AccountDTO.accountName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accountType', full_name='api.AccountDTO.accountType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='api.AccountDTO.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=191,
)


_CREATEACCOUNTCOMMAND = _descriptor.Descriptor(
  name='CreateAccountCommand',
  full_name='api.CreateAccountCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='api.CreateAccountCommand.account', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=249,
)


_CREATEACCOUNTDOCUMENT = _descriptor.Descriptor(
  name='CreateAccountDocument',
  full_name='api.CreateAccountDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=274,
)


_GETACCOUNTCOMMAND = _descriptor.Descriptor(
  name='GetAccountCommand',
  full_name='api.GetAccountCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountName', full_name='api.GetAccountCommand.accountName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=316,
)


_GETACCOUNTDOCUMENT = _descriptor.Descriptor(
  name='GetAccountDocument',
  full_name='api.GetAccountDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='api.GetAccountDocument.account', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=372,
)

_ERRORDTO.fields_by_name['errorCode'].enum_type = _ERRORCODEDTO
_CREATEACCOUNTCOMMAND.fields_by_name['account'].message_type = _ACCOUNTDTO
_GETACCOUNTDOCUMENT.fields_by_name['account'].message_type = _ACCOUNTDTO
DESCRIPTOR.message_types_by_name['ErrorDTO'] = _ERRORDTO
DESCRIPTOR.message_types_by_name['AccountDTO'] = _ACCOUNTDTO
DESCRIPTOR.message_types_by_name['CreateAccountCommand'] = _CREATEACCOUNTCOMMAND
DESCRIPTOR.message_types_by_name['CreateAccountDocument'] = _CREATEACCOUNTDOCUMENT
DESCRIPTOR.message_types_by_name['GetAccountCommand'] = _GETACCOUNTCOMMAND
DESCRIPTOR.message_types_by_name['GetAccountDocument'] = _GETACCOUNTDOCUMENT
DESCRIPTOR.enum_types_by_name['ErrorCodeDTO'] = _ERRORCODEDTO

ErrorDTO = _reflection.GeneratedProtocolMessageType('ErrorDTO', (_message.Message,), dict(
  DESCRIPTOR = _ERRORDTO,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.ErrorDTO)
  ))
_sym_db.RegisterMessage(ErrorDTO)

AccountDTO = _reflection.GeneratedProtocolMessageType('AccountDTO', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTDTO,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.AccountDTO)
  ))
_sym_db.RegisterMessage(AccountDTO)

CreateAccountCommand = _reflection.GeneratedProtocolMessageType('CreateAccountCommand', (_message.Message,), dict(
  DESCRIPTOR = _CREATEACCOUNTCOMMAND,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.CreateAccountCommand)
  ))
_sym_db.RegisterMessage(CreateAccountCommand)

CreateAccountDocument = _reflection.GeneratedProtocolMessageType('CreateAccountDocument', (_message.Message,), dict(
  DESCRIPTOR = _CREATEACCOUNTDOCUMENT,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.CreateAccountDocument)
  ))
_sym_db.RegisterMessage(CreateAccountDocument)

GetAccountCommand = _reflection.GeneratedProtocolMessageType('GetAccountCommand', (_message.Message,), dict(
  DESCRIPTOR = _GETACCOUNTCOMMAND,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.GetAccountCommand)
  ))
_sym_db.RegisterMessage(GetAccountCommand)

GetAccountDocument = _reflection.GeneratedProtocolMessageType('GetAccountDocument', (_message.Message,), dict(
  DESCRIPTOR = _GETACCOUNTDOCUMENT,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.GetAccountDocument)
  ))
_sym_db.RegisterMessage(GetAccountDocument)


# @@protoc_insertion_point(module_scope)
