# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/py_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lib/py_proto.proto',
  package='api',
  serialized_pb=_b('\n\x12lib/py_proto.proto\x12\x03\x61pi\"F\n\x08\x45rrorDTO\x12$\n\terrorCode\x18\x01 \x02(\x0e\x32\x11.api.ErrorCodeDTO\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x02(\t\"G\n\x07PingDTO\x12\x0b\n\x03msg\x18\x01 \x02(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x02(\t\x12\x1e\n\x06pingId\x18\x03 \x02(\x0e\x32\x0e.api.PingIdDTO\")\n\x0bPingCommand\x12\x1a\n\x04ping\x18\x01 \x02(\x0b\x32\x0c.api.PingDTO\"*\n\x0cPingDocument\x12\x1a\n\x04ping\x18\x01 \x02(\x0b\x32\x0c.api.PingDTO*e\n\x0c\x45rrorCodeDTO\x12\x1a\n\x16INCORRECT_CONTENT_TYPE\x10\x02\x12\x13\n\x0fINVALID_REQUEST\x10\x03\x12\x0f\n\x0bINVALID_MSG\x10\x04\x12\x13\n\x0fINVALID_CHANNEL\x10\x05*\x1f\n\tPingIdDTO\x12\x08\n\x04PING\x10\x01\x12\x08\n\x04PONG\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ERRORCODEDTO = _descriptor.EnumDescriptor(
  name='ErrorCodeDTO',
  full_name='api.ErrorCodeDTO',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INCORRECT_CONTENT_TYPE', index=0, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_REQUEST', index=1, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_MSG', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_CHANNEL', index=3, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=259,
  serialized_end=360,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODEDTO)

ErrorCodeDTO = enum_type_wrapper.EnumTypeWrapper(_ERRORCODEDTO)
_PINGIDDTO = _descriptor.EnumDescriptor(
  name='PingIdDTO',
  full_name='api.PingIdDTO',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PONG', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=362,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_PINGIDDTO)

PingIdDTO = enum_type_wrapper.EnumTypeWrapper(_PINGIDDTO)
INCORRECT_CONTENT_TYPE = 2
INVALID_REQUEST = 3
INVALID_MSG = 4
INVALID_CHANNEL = 5
PING = 1
PONG = 2



_ERRORDTO = _descriptor.Descriptor(
  name='ErrorDTO',
  full_name='api.ErrorDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='api.ErrorDTO.errorCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='api.ErrorDTO.errorMessage', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=97,
)


_PINGDTO = _descriptor.Descriptor(
  name='PingDTO',
  full_name='api.PingDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='api.PingDTO.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='api.PingDTO.channel', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pingId', full_name='api.PingDTO.pingId', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=170,
)


_PINGCOMMAND = _descriptor.Descriptor(
  name='PingCommand',
  full_name='api.PingCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ping', full_name='api.PingCommand.ping', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=213,
)


_PINGDOCUMENT = _descriptor.Descriptor(
  name='PingDocument',
  full_name='api.PingDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ping', full_name='api.PingDocument.ping', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=257,
)

_ERRORDTO.fields_by_name['errorCode'].enum_type = _ERRORCODEDTO
_PINGDTO.fields_by_name['pingId'].enum_type = _PINGIDDTO
_PINGCOMMAND.fields_by_name['ping'].message_type = _PINGDTO
_PINGDOCUMENT.fields_by_name['ping'].message_type = _PINGDTO
DESCRIPTOR.message_types_by_name['ErrorDTO'] = _ERRORDTO
DESCRIPTOR.message_types_by_name['PingDTO'] = _PINGDTO
DESCRIPTOR.message_types_by_name['PingCommand'] = _PINGCOMMAND
DESCRIPTOR.message_types_by_name['PingDocument'] = _PINGDOCUMENT
DESCRIPTOR.enum_types_by_name['ErrorCodeDTO'] = _ERRORCODEDTO
DESCRIPTOR.enum_types_by_name['PingIdDTO'] = _PINGIDDTO

ErrorDTO = _reflection.GeneratedProtocolMessageType('ErrorDTO', (_message.Message,), dict(
  DESCRIPTOR = _ERRORDTO,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.ErrorDTO)
  ))
_sym_db.RegisterMessage(ErrorDTO)

PingDTO = _reflection.GeneratedProtocolMessageType('PingDTO', (_message.Message,), dict(
  DESCRIPTOR = _PINGDTO,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.PingDTO)
  ))
_sym_db.RegisterMessage(PingDTO)

PingCommand = _reflection.GeneratedProtocolMessageType('PingCommand', (_message.Message,), dict(
  DESCRIPTOR = _PINGCOMMAND,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.PingCommand)
  ))
_sym_db.RegisterMessage(PingCommand)

PingDocument = _reflection.GeneratedProtocolMessageType('PingDocument', (_message.Message,), dict(
  DESCRIPTOR = _PINGDOCUMENT,
  __module__ = 'lib.py_proto_pb2'
  # @@protoc_insertion_point(class_scope:api.PingDocument)
  ))
_sym_db.RegisterMessage(PingDocument)


# @@protoc_insertion_point(module_scope)
