FROM python:3.5

# adding code
WORKDIR /app/pikachu
ADD requirements.txt /app/pikachu

# install
RUN pip install -r requirements.txt

ADD . /app/pikachu

EXPOSE 8080
ENTRYPOINT gunicorn --bind 0.0.0.0:8080 pikachu.app:api
